// Målesæt: hver katalogtype med demodata, så højden kan måles i hver gitterbredde (23.1 gridmodel).
import type { GalleryEntry } from "../types.js";
const C = "CVR-1-99000001";
const P = "CVR-3-4000000002";
const c = (type: string, extra: Record<string, unknown> = {}) => ({ type, company: C, ...extra });
const p = (type: string, extra: Record<string, unknown> = {}) => ({ type, person: P, ...extra });
const specs: Record<string, Record<string, unknown>> = {
  LassoCompanyHead: c("LassoCompanyHead"),
  LassoKeyFigureCards: c("LassoKeyFigureCards"),
  LassoKeyValueList: c("LassoKeyValueList"),
  "LassoKeyValueList (financials)": c("LassoKeyValueList", { variant: "financials" }),
  LassoContact: c("LassoContact"),
  LassoContactPersons: c("LassoContactPersons"),
  LassoShortcuts: c("LassoShortcuts"),
  LassoTextSections: c("LassoTextSections"),
  LassoTimeline: c("LassoTimeline"),
  LassoNews: c("LassoNews"),
  LassoBarChart: c("LassoBarChart"),
  LassoGroupedBarChart: c("LassoGroupedBarChart"),
  LassoLineChart: c("LassoLineChart"),
  LassoStackedBarChart: c("LassoStackedBarChart"),
  LassoWaterfallChart: c("LassoWaterfallChart"),
  LassoShareBars: c("LassoShareBars"),
  LassoKeyFigureGauge: c("LassoKeyFigureGauge"),
  LassoMultiYearTable: c("LassoMultiYearTable"),
  LassoIncomeStatement: c("LassoIncomeStatement"),
  LassoBalanceSheet: c("LassoBalanceSheet"),
  LassoCashFlow: c("LassoCashFlow"),
  LassoFinancialStatements: c("LassoFinancialStatements"),
  LassoPersonList: c("LassoPersonList"),
  LassoOwnerList: c("LassoOwnerList"),
  LassoBeneficialOwners: c("LassoBeneficialOwners"),
  LassoOwnershipDiagram: c("LassoOwnershipDiagram"),
  LassoRelations: c("LassoRelations"),
  LassoRiskObservations: c("LassoRiskObservations"),
  LassoScoreGauge: c("LassoScoreGauge"),
  LassoProductionUnits: c("LassoProductionUnits"),
  LassoProperties: c("LassoProperties"),
  LassoMap: c("LassoMap"),
  LassoRegistration: c("LassoRegistration"),
  LassoMergers: c("LassoMergers"),
  LassoAnnouncements: c("LassoAnnouncements"),
  LassoPublications: c("LassoPublications"),
  LassoLivestock: { type: "LassoLivestock", company: "CVR-1-99000013" },
  LassoCompareTable: { type: "LassoCompareTable", companies: [C, "CVR-1-99000004", "CVR-1-99000008"] },
  LassoRanking: { type: "LassoRanking", companies: [C, "CVR-1-99000004", "CVR-1-99000008", "CVR-1-99000005"] },
  LassoCompanyTable: { type: "LassoCompanyTable", source: "search", search: { query: "", limit: 8 } },
  LassoPersonHead: p("LassoPersonHead"),
  LassoPersonRoles: p("LassoPersonRoles"),
  LassoPersonNetwork: p("LassoPersonNetwork"),
  LassoPersonRisk: p("LassoPersonRisk"),
  LassoPersonFacts: p("LassoPersonFacts"),
  LassoPersonStats: p("LassoPersonStats"),
  LassoChangeFeed: { type: "LassoChangeFeed" },
  LassoHeatmap: { type: "LassoHeatmap" },
};
export const entries: GalleryEntry[] = Object.entries(specs).map(([name, comp]) => ({
  nr: "M." + name,
  title: name,
  spec: { title: name, layout: "stack", components: [{ ...comp, width: "full" }] },
}));
